extends: airbnb
rules:
  class-methods-use-this: 0
  no-console: [1, { allow: ['info', 'warn', 'error']}]
  no-underscore-dangle: 0
  react/jsx-one-expression-per-line: 0
  react/jsx-no-bind: 0
  react/no-unknown-property: [1, { ignore: ['class'] }]
globals:
  document: true
